# Generated by Django 4.2.7 on 2023-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'User_table',
            },
        ),
    ]
