# Generated by Django 4.2.7 on 2023-11-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='U',
        ),
    ]
