# Generated by Django 4.2.7 on 2023-11-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User_table',
        ),
    ]
