# Generated by Django 4.2.7 on 2023-11-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_delete_details_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('land', 'Land'), ('home', 'Home')], max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
